name: New Project Request
description: Request new project to be onboarded to Clean Dependency Project
title: "CDP-INTAkE: "
labels: [new-project, Needs Triage]

body:
- type: markdown
  attributes:
    value: "Thanks for taking the time to fill out this request! Our Project members shall review and update with next steps."
